### ISSUE TITLE
Server cannot launch on kinetic due to tornado not being found

### ISSUE THREAD

**Issue by msmcconnell** [RobotWebTools/rosbridge_suite#490] opened 2020-04-27 19:18 UTC
After recent updates (not clear exactly when), I can no longer use rosbridge with ROS kinetic. The tornado module fails to be found. This was working in February. 

## Expected Behavior
After running 
```
sudo apt-get update
sudo apt-get install ros-kinetic-rosbridge-server
```
I can run the following without experiencing crashes. 
```
roslaunch rosbridge_server rosbridge_websocket.launch
``` 

## Actual Behavior
The tornado module cannot be found causing the server to crash. 
```
carma@ubuntu:/$ roslaunch rosbridge_server rosbridge_websocket.launch
... logging to /home/carma/.ros/log/75b22a74-88ba-11ea-a6a8-000c29e8fc0e/roslaunch-ubuntu-41.log
Checking log directory for disk usage. This may take awhile.
Press Ctrl-C to interrupt
Done checking log file disk usage. Usage is <1GB.

started roslaunch server http://ubuntu:35403/

SUMMARY
========

PARAMETERS
 * /rosapi/params_glob: [*]
 * /rosapi/services_glob: [*]
 * /rosapi/topics_glob: [*]
 * /rosbridge_websocket/address: 0.0.0.0
 * /rosbridge_websocket/authenticate: False
 * /rosbridge_websocket/bson_only_mode: False
 * /rosbridge_websocket/delay_between_messages: 0
 * /rosbridge_websocket/fragment_timeout: 600
 * /rosbridge_websocket/max_message_size: None
 * /rosbridge_websocket/params_glob: [*]
 * /rosbridge_websocket/port: 9090
 * /rosbridge_websocket/retry_startup_delay: 5
 * /rosbridge_websocket/services_glob: [*]
 * /rosbridge_websocket/topics_glob: [*]
 * /rosbridge_websocket/unregister_timeout: 10
 * /rosbridge_websocket/use_compression: False
 * /rosbridge_websocket/websocket_external_port: 9090
 * /rosbridge_websocket/websocket_ping_interval: 0
 * /rosbridge_websocket/websocket_ping_timeout: 30
 * /rosdistro: kinetic
 * /rosversion: 1.12.14

NODES
  /
    rosapi (rosapi/rosapi_node)
    rosbridge_websocket (rosbridge_server/rosbridge_websocket)

auto-starting new master
process[master]: started with pid [51]
ROS_MASTER_URI=http://localhost:11311

setting /run_id to 75b22a74-88ba-11ea-a6a8-000c29e8fc0e
process[rosout-1]: started with pid [64]
started core service [/rosout]
process[rosbridge_websocket-2]: started with pid [72]
2020-04-27 19:08:22+0000 [-] Log opened.
2020-04-27 19:08:22+0000 [-] Traceback (most recent call last):
2020-04-27 19:08:22+0000 [-]   File "/opt/ros/kinetic/lib/rosbridge_server/rosbridge_websocket", line 48, in <module>
2020-04-27 19:08:22+0000 [-]     from rosbridge_server import ClientManager
2020-04-27 19:08:22+0000 [-]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbridge_server/__init__.py", line 2, in <module>
2020-04-27 19:08:22+0000 [-]     from .websocket_handler import RosbridgeWebSocket
2020-04-27 19:08:22+0000 [-]   File "/opt/ros/kinetic/lib/python2.7/dist-packages/rosbridge_server/websocket_handler.py", line 43, in <module>
2020-04-27 19:08:22+0000 [-]     from tornado import version_info as tornado_version_info
2020-04-27 19:08:22+0000 [-] ImportError: No module named tornado
process[rosapi-3]: started with pid [82]
[rosbridge_websocket-2] process has died [pid 72, exit code 1, cmd /opt/ros/kinetic/lib/rosbridge_server/rosbridge_websocket __name:=rosbridge_websocket __log:=/home/carma/.ros/log/75b22a74-88ba-11ea-a6a8-000c29e8fc0e/rosbridge_websocket-2.log].
log file: /home/carma/.ros/log/75b22a74-88ba-11ea-a6a8-000c29e8fc0e/rosbridge_websocket-2*.log
^C[rosapi-3] killing on exit
[rosout-1] killing on exit
[master] killing on exit
shutting down processing monitor...
... shutting down processing monitor complete
done
```

## Steps to Reproduce the Problem

On clean install of Ubuntu 16.04 run the two commands listed in expected behavior after a ros-desktop-full installation. 
## Specifications

  - ROS Version (`echo $ROS_DISTRO`): kinetic
  - OS Version (`grep DISTRIB_CODENAME /etc/lsb-release`): DISTRIB_CODENAME=xenial
  - Rosbridge Version (`roscat rosbridge_server package.xml | grep '<version>'`): <version>0.11.5</version>

  - Twisted Version (`python -c 'import twisted; print twisted.version'`): [twisted, version 16.0.0]

**Comment by mvollrath** [comment] 2020-04-27 19:56
Duplicate of #484

**Closed by mvollrath** 2020-04-27 19:56 UTC
