### ISSUE TITLE
Serialization buffer size

### ISSUE THREAD

**Issue by RainCT** [RobotWebTools/rosbridge_suite#69] opened 2013-12-13 17:07 UTC
Topic Subscriber buffers are currently infinite. This is a problem on systems with limited resources when there's a lot of big entries to serialize. Ideally the buffer sizes of the rosbridge subscribers would be taken into account.

**Comment by RalphCodesTheInternet** [comment] 2021-09-16 09:16
I am having laggy issues where messages keep being published for a while even though the publisher has been terminated. Could this be because of the infinite buffer?

**Comment by amacneil** [comment] 2021-12-17 00:25
Closing this issue since it has been open for 8 years. @RalphCodesTheInternet if you are still having issues can you please open a new issue with steps to reproduce?

**Closed by amacneil** 2021-12-17 00:25 UTC
Labels: enhancement, Bug Fix
